export {
  blockedOperationPreview,
  defineActingFor,
  defineOperation,
  defineOperationDescriptor,
  defineOperationMetadata,
  defineCaller,
  defineTrellis,
  executeOperationRef,
  getOperationMetadata,
  implementOperation,
  isOperationPreviewEnvelope,
  operationEffect,
  operationIssue,
  operationPreview,
  operationPreviewEffectValidator,
  operationPreviewIssueValidator,
  operationPreviewValidator,
  previewOf,
  previewOperationRef,
  projectOperationRef,
  transportExecuteOperationRef,
  trellisBackendLaneMetadataKey,
  trellisOperationMetadataKey,
  trellisOperationProjectionMetadataKey,
  unsafe,
} from '../functions/index.js'

export {
  canonicalizeForwardingArgs,
  createIdentityForwardingEnvelope,
  hashForwardingArgs,
  IdentityForwardingEnvelopeError,
  verifyIdentityForwardingEnvelope,
} from '../identity-forwarding/envelope.js'
export {
  clearIdentityForwardingContext,
  createIdentityForwardingEnvelopeArgs,
  extractSubject,
  getForwardedActingFor,
  getForwardedCaller,
  getIdentityForwarding,
  getIdentityForwardingKeyProductionIssue,
  setIdentityForwardingContext,
  withIdentityForwarding,
} from '../identity-forwarding/index.js'

export type {
  AppIdentityAccessor,
  DefaultCaller,
  ActingFor,
  ActingForAccessor,
  ActingForDefinition,
  FunctionsCtxExtension,
  InferOperationLoaded,
  InferOperationPreview,
  InferOperationResult,
  McpWriteSafety,
  OperationDefinition,
  OperationDescriptor,
  OperationIdOf,
  OperationKind,
  OperationMetadataDefinition,
  OperationExecutionsById,
  OperationPreviewEffect,
  OperationPreviewEnvelope,
  OperationPreviewIssue,
  OperationProjectionRef,
  OperationPreviewsById,
  OperationsById,
  CallerAccessor,
  CallerDefinition,
  RegisteredOperationDefinition,
  RegisteredOperationExecution,
  RegisteredOperationId,
  RegisteredOperationPreview,
  RegisteredOperationProjections,
  RegisteredOperations,
  StructuredGuard,
  StructuredHandlerDefinition,
  StructuredLoadedValue,
  TrellisOperationMetadata,
  TrellisOperationProjectionMetadata,
  TrellisBackendLane,
  TrellisUnsafePermit,
  ValidateOperationDefinition,
  ValidateOperationId,
  ValidateOperationProjection,
  ValidateOperationProjectionRef,
  ValidateRegisteredOperationId,
} from '../functions/index.js'

export type {
  CreateIdentityForwardingEnvelopeOptions,
  IdentityForwardingEnvelopePayload,
  IdentityForwardingPurpose,
  IdentityForwardingTransport,
  VerifyIdentityForwardingEnvelopeOptions,
} from '../identity-forwarding/envelope.js'
