import { beforeAll, describe, expect, it } from 'vitest'

describe('auth entrypoint exports', () => {
  let authApi: typeof import('../../src/runtime/auth/index')
  let identityForwardingApi: typeof import('../../src/runtime/identity-forwarding/index')
  let visibilityApi: typeof import('../../src/runtime/visibility/index')

  beforeAll(async () => {
    authApi = await import('../../src/runtime/auth/index')
    identityForwardingApi = await import('../../src/runtime/identity-forwarding/index')
    visibilityApi = await import('../../src/runtime/visibility/index')
  })

  it('exports the canonical auth primitives', () => {
    expect(authApi).toHaveProperty('and')
    expect(authApi).toHaveProperty('or')
    expect(authApi).toHaveProperty('defineAppIdentity')
    expect(authApi).toHaveProperty('defineGuard')
    expect(authApi).toHaveProperty('authRequired')
    expect(authApi).toHaveProperty('isAuthRequiredGuard')
    expect(authApi).toHaveProperty('isGuard')
    expect(authApi).toHaveProperty('open')
    expect(authApi).toHaveProperty('enforce')
    expect(authApi).toHaveProperty('can')
    expect(authApi).toHaveProperty('deny')
    expect(authApi).toHaveProperty('getAuth')
    expect(authApi).toHaveProperty('requireAuth')
    expect(authApi).toHaveProperty('requireRecord')
    expect(authApi).toHaveProperty('ensureTenant')
    expect(authApi).toHaveProperty('loadTenantResource')
    expect(authApi).toHaveProperty('defineBetterAuth')
    expect(authApi).toHaveProperty('defineAccessContext')
    expect(authApi).toHaveProperty('getSubjectKind')
    expect(authApi).toHaveProperty('getSubjectValue')
    expect(authApi).toHaveProperty('isSubjectKind')
    expect(authApi).not.toHaveProperty('withCan')
    expect(authApi).not.toHaveProperty('definePermissions')
    expect(authApi).not.toHaveProperty('createDefaultGetAppIdentity')
    expect(authApi).not.toHaveProperty('defineAppIdentityExtension')
    expect(authApi).not.toHaveProperty('defineAppIdentityFromMembership')
    expect(authApi).not.toHaveProperty('createFunctions')

    expect(identityForwardingApi).toHaveProperty('getIdentityForwarding')
    expect(identityForwardingApi).toHaveProperty('createIdentityForwardingEnvelope')
    expect(identityForwardingApi).toHaveProperty('withIdentityForwarding')
    expect(identityForwardingApi).toHaveProperty('setIdentityForwardingContext')
    expect(identityForwardingApi).toHaveProperty('clearIdentityForwardingContext')
    expect(identityForwardingApi).toHaveProperty('getForwardedActingFor')
    expect(visibilityApi).toHaveProperty('defineRecordAccess')
    expect(visibilityApi).toHaveProperty('defineRedaction')
  })
})
