import {
  renderComponentBridgeModule,
  renderComponentBridgeFiles,
  resolveConvexAppBinding,
  stripBridgeManagedBlock,
} from '@lupinum/trellis-bridge/manifest'
import { describe, expect, it } from 'vitest'

describe('component bridge manifest helpers', () => {
  it('prefers better-auth registration as the app insertion anchor', () => {
    const source = `
import betterAuth from '@convex-dev/better-auth/convex.config'
import { defineApp } from 'convex/server'

const cmsApp = defineApp()

cmsApp.use(betterAuth, {
  name: 'betterAuth',
})
`

    const binding = resolveConvexAppBinding(source)

    expect(binding).toMatchObject({
      appName: 'cmsApp',
      anchorKind: 'betterAuth',
    })
    expect(binding?.anchorText).toContain("name: 'betterAuth'")
  })

  it('falls back to multiline defineApp bindings when better-auth is absent', () => {
    const source = `
import { defineApp } from 'convex/server'

const aliasedApp =
  defineApp()

export default aliasedApp
`

    expect(resolveConvexAppBinding(source)).toMatchObject({
      appName: 'aliasedApp',
      anchorKind: 'defineApp',
    })
  })

  it('removes existing managed blocks by package and key', () => {
    const source = `
const app = defineApp()

// @trellis-managed-start: @example/component convex-component
app.use(component)
// @trellis-managed-end: @example/component convex-component

export default app
`

    expect(
      stripBridgeManagedBlock(source, {
        packageName: '@example/component',
        key: 'convex-component',
      }),
    ).not.toContain('app.use(component)')
  })

  it('renders deterministic declarative bridge module stubs', () => {
    expect(
      renderComponentBridgeModule({
        relativePath: 'convex/example.ts',
        factory: {
          name: 'createExampleBridge',
          from: '@example/component/bridge/example',
        },
        imports: [
          { named: ['components'], from: '../_generated/api' },
          { named: ['component'], from: './_principal' },
        ],
        factoryArgs: {
          component: 'component',
          components: 'components.example.public',
        },
        exportNames: ['getPage', 'list'],
      }),
    ).toBe(
      [
        '// AUTO-GENERATED by Trellis - do not edit manually',
        "import { createExampleBridge } from '@example/component/bridge/example'",
        "import { components } from '../_generated/api'",
        "import { component } from './_principal'",
        '',
        'const bridge = createExampleBridge({',
        '  component: component,',
        '  components: components.example.public',
        '})',
        '',
        'export const getPage = bridge.getPage',
        'export const list = bridge.list',
        '',
      ].join('\n'),
    )
  })

  it('rejects duplicate exports and invalid component paths in declarative modules', async () => {
    await expect(
      renderComponentBridgeFiles({
        packageName: '@example/component',
        version: '1.0.0',
        modules: [
          {
            relativePath: 'convex/example.ts',
            factory: { name: 'createExampleBridge', from: '@example/component/bridge/example' },
            imports: [],
            factoryArgs: { components: 'components.example;bad' },
            exportNames: ['one'],
          },
        ],
      }),
    ).rejects.toThrow('Invalid bridge module')

    expect(() =>
      renderComponentBridgeModule({
        relativePath: 'convex/example.ts',
        factory: { name: 'createExampleBridge', from: '@example/component/bridge/example' },
        imports: [],
        factoryArgs: {},
        exportNames: ['one', 'one'],
      }),
    ).toThrow('duplicate export')
  })

  it('rejects bridge file and managed edit paths that escape the app root', async () => {
    await expect(
      renderComponentBridgeFiles({
        packageName: '@example/component',
        version: '1.0.0',
        renderFiles: [{ relativePath: '../outside.ts', content: '' }],
      }),
    ).rejects.toThrow(/unsafe relative path/)

    await expect(
      renderComponentBridgeFiles({
        packageName: '@example/component',
        version: '1.0.0',
        modules: [
          {
            relativePath: '/tmp/outside.ts',
            factory: { name: 'createExampleBridge', from: '@example/component/bridge/example' },
            imports: [],
            factoryArgs: {},
            exportNames: ['one'],
          },
        ],
      }),
    ).rejects.toThrow(/unsafe relative path/)

    const { renderComponentBridgeManagedEdits } = await import('@lupinum/trellis-bridge/manifest')
    await expect(
      renderComponentBridgeManagedEdits({
        packageName: '@example/component',
        version: '1.0.0',
        managedEdits: [{ relativePath: 'convex/../outside.ts', apply: () => '' }],
      }),
    ).rejects.toThrow(/unsafe relative path/)
  })
})
